//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptowalletProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersBankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersBankAccount()
        {
            this.UsersTransactions = new HashSet<UsersTransaction>();
            this.UsersTransactions1 = new HashSet<UsersTransaction>();
        }
    
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public int Currency { get; set; }
        public decimal Amount { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersTransaction> UsersTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersTransaction> UsersTransactions1 { get; set; }
    }
}
